server:
  port: 8700

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalogo-produtos
          uri: lb://catalogo-produtos
          predicates:
            - Path=/api/produtos/**
          filters:
            - StripPrefix=0
        - id: simulador-pedidos
          uri: lb://simulador-pedidos
          predicates:
            - Path=/api/pedidos/**
          filters:
            - StripPrefix=0
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always